#!/usr/bin/env node
var GitLab = require('gitlab');
var map = require('lodash/map');

var token = process.env.GITLAB_TOKEN;

var gitlab = new GitLab({
  url: 'https://gitlab.com',
  token: token,
});

var s = gitlab.projects.all(function(projects) {
  console.log(JSON.stringify(projects, null, 2));
});
